volumes:
  db-data:

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db

  backend:
    image: ghcr.io/meal-tiger/meal-tiger-backend:development
    restart: always
    depends_on:
      - mongo
    environment:
      - OIDC_AUTHENTICATION_ENABLED=true
      - OIDC_AUTHENTICATION_PROVIDER_URL=https://auth.lifeminer.de/realms/meal-tiger-test
      - OIDC_CLIENT_ID=mealtiger
      - DBURL=mongodb://mongo
      - ALLOWED_ORIGINS=*
    links:
      - mongo
    ports:
      - 8080:8080

  node:
    image: "node:18-alpine"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - REACT_APP_OIDC_CONFIGURATION_ENDPOINT=https://auth.lifeminer.de/realms/meal-tiger-test/.well-known/openid-configuration
      - REACT_APP_OIDC_CLIENT_ID=mealtiger 
    volumes:
      - ./react-frontend/:/home/node/app
    ports:
      - 3000:3000
    command: sh -c "npm i && npm start"