services:
  frontend:
    image: "ghcr.io/meal-tiger/meal-tiger-frontend:main"
    environment:
      - API_URL=http://localhost:8080
      - OIDC_CONFIGURATION_ENDPOINT=http://localhost:8090/realms/master/.well-known/openid-configuration
      - OIDC_CLIENT_ID=mealtiger
    ports:
      - 80:80